import Head from 'next/head';
import Feed from '../components/Feed';
import Header from '../components/Header';
import Modal from '../components/Modal';

export default function Home() {
  return (
    <>
      <Head>
        <title>Instagram 2.0</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='bg-gray-200 min-h-screen  scrollbar-none'>
        <Header />
        <Feed />
        <Modal />
      </div>
    </>
  );
}
